const Products = [
	{
		id: 1,
		img: "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
		name: "Old Fashioned",
		title: "Classic cocktail",
		type: "Avec alcool",
	},
	{
		id: 2,
		img: "https://www.thecocktaildb.com/images/media/drink/spvvxp1468924425.jpg",
		name: "Strawberry Lemonade",
		title: "Lemonade",
		type: "Sans alcool",
	},
	{
		id: 3,
		img: "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
		name: "Ace",
		title: "Martini Glass",
		type: "Avec alcool",
	},
	{
		id: 4,
		img: "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
		name: "Adam",
		title: "Cocktail",
		type: "Avec alcool",
	},
	{
		id: 5,
		img: "https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg",
		name: "AT&T",
		title: "Highball",
		type: "Avec alcool",
	},
	{
		id: 6,
		img: "https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg",
		name: "ACID",
		title: "Shot",
		type: "Avec alcool",
	},
	{
		id: 7,
		img: "https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg",
		name: "A. J.",
		title: "Cocktail",
		type: "Avec alcool",
	},

	{
		id: 8,
		img: "https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg",
		name: "Karsk",
		title: "Highball",
		type: "Avec alcool",
	},
	{
		id: 9,
		img: "https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg",
		name: "Melya",
		title: "Coffee Mug",
		type: "Avec alcool",
	},
	{
		id: 10,
		img: "https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg",
		name: "Affair",
		title: "Highball",
		type: "Avec alcool",
	},
	{
		id: 11,
		img: "https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg",
		name: "Boxcar",
		title: "Whiskey sour",
		type: "Avec alcool",
	},
	{
		id: 12,
		img: "https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg",
		name: "Orgasm",
		title: "Cocktail",
		type: "Sans alcool",
	},
	{
		id: 13,
		img: "https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg",
		name: "Apello",
		title: "Collins",
		type: "Sans alcool",
	},
];
export default Products;
